#!/bin/bash

WAN_IP=

while [[ $(curl -s https://icanhazip.com/) = $WAN_IP || \
        ($(curl -v --silent https://www.privateinternetaccess.com/what-is-my-ip) =~ 'You are not connected to PIA' && \
        ! $(curl -v --silent https://www.privateinternetaccess.com/what-is-my-ip) =~ 'You are connected to PIA') ]]
do
  echo "VPN not up, waiting a bit"
  sleep 5
done